---
title: "Comparision between Berlin and NRW in regards to number of N per sequences"
output: html_document
date: "2022-09-26"
---

The below histogram represents the number of N per sequences
```{r}
data <- read.csv("Desktop/Berlin_Number_of_N.csv")
#data[, 3] <- sapply(data[, 3], as.numeric)
data$seq_count <- NULL #removing seq_count from the Berlin dataset
head(data)
sapply(data[1,],class) #to know integer class
Berlin <- data$n_count
hist(Berlin , xlab = "Number of N per Sequences" , border = "blue")
```

The below histogram represents the number of N per sequences
```{r}
data <- read.csv("Desktop/NRW_Number_of_N.csv")
#data[, 3] <- sapply(data[, 3], as.numeric)
data$seq_count <- NULL #removing seq_count from the NRW dataset
head(data)
sapply(data[1,],class) #to know integer class
NRW <- data$n_count
hist(NRW , xlab = "Number of N per Sequences" , border = "blue")
```
The below boxplot shows the distribution of N-content in Berlin and NRW
```{r}
data1 <- read.csv("Desktop/NRW_Number_of_N.csv")
data2 <- read.csv("Desktop/Berlin_Number_of_N.csv")
# prepare the data
NRW_count1 <- data1$n_count
Berlin_count2 <- data2$n_count
#We can draw multiple boxplots in a single plot, by passing in a list, data frame or multiple vectors.
#considering the Berlin and NRW field of n_count dataset.
boxplot(NRW_count1, Berlin_count2,
main = "Distribution of N-Content in the datasets",
at = c(1,2),
names = c("NRW", "Berlin"),
las = 2,
col = c("orange","red"),
border = "brown",
horizontal = TRUE,
notch = TRUE
)

```






